name: Bug Report
description: File a bug report.
title: '[Bug]: '
labels: ['bug']

body:
  - type: input
    id: companion-version
    attributes:
      label: Version
      description: What version of Companion are you seeing this issue on? (you can see find this on the top left corner of the Companion interface)
      placeholder: v4.0.0
    validations:
      required: true
  - type: input
    id: module-version
    attributes:
      label: Version
      description: What version of the module are you seeing this issue on? (you can find this in the module's settings by clicking the help icon)
      placeholder: v2.0.1
    validations:
      required: true
  - type: input
    id: firmware-version
    attributes:
      label: Version
      description: What version of WING Firmware are you seeing this issue on? (you can see find this in the WING settings)
      placeholder: v3.0.6
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Describe the bug
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: 'A bug happened!'
    validations:
      required: true
