blank_issues_enabled: false
contact_links:
  - name: Bog or Feature for Companion itself
    url: https://github.com/bitfocus/companion/issues
    about: Report it against the companion itself, to get the relevant people notified.
